### ISSUE TITLE
Set up and deploy Team MySQL database

### ISSUE THREAD

**Issue by TiciaD** [chingu-voyages/v41-bears-team-20#16]
**__Task Description__**
Set up MySQL database

**__Technical Considerations__**
Include any technical considerations including architecture (e.g. API), required libraries, etc.

**__Additional Considerations__**
Any supplemental information including unresolved questions, links to external resources, screenshots, etc.

**Comment by riboney** [comment]
Closing this issue since I have setup this up already 
![image](https://user-images.githubusercontent.com/14286113/199859277-6456bbd9-5785-488f-a41e-388d3c61e17a.png)

There are some basic instructions in the repo wiki if anyone wanted to set it up on their own and connect it with the app
